# -*- coding: utf-8 -*-
"""Prac5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBO1xNQ-LApXgU3erK2mcRtAx6HG12oH
"""

import pandas as pd

data = pd.read_csv('https://gist.githubusercontent.com/nstokoe/7d4717e96c21b8ad04ec91f361b000cb/raw/bf95a2e30fceb9f2ae990eac8379fc7d844a0196/weight-height.csv')

data

data.isna().sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data, x = 'Gender', color='red')

sns.boxplot(x=data['Height'], color='orange')

sns.boxplot(x=data['Weight'], color='purple')

data.head(1)

data2 = data.iloc[:, 1:]
data2

data2.corr()

sns.heatmap(data2.corr(),cmap="Purples", annot=True)

x = data.iloc[:, 1:2].values

y = data.iloc[:, 2].values

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x, y)
x = pd.DataFrame(scaler.transform(x))

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

lr.fit(x_train, y_train)

lr.coef_

lr.intercept_

lr.score(x_test, y_test)

lr.score(x_train, y_train)

lr.predict([[61]])

import pickle
with open('prac5model', 'wb') as f1:
  pickle.dump(lr, f1)

with open('prac5model', 'rb') as f1:
  model = pickle.load(f1)

model.score(x_test, y_test)

model.predict([[61]])

from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(x_train, y_train)

ridge_model.score(x_test, y_test)

lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train, y_train)

lasso_model.score(x_test, y_test)

